window.opacity = 0.5


[terminal.shell]
program = "/usr/bin/zsh"

[window.padding]
y = 0
x = 0

[font] 
size = 14.0
normal.family = "JetBrainsMono NF"
normal.style = "Regular"
bold.family = "JetBrainsMono NF"
bold.style = "Bold"
italic.family = "JetBrainsMono NF"
italic.style = "Italic"
bold_italic.family = "JetBrainsMono NF"
bold_italic.style = "Bold Italic"

[cursor]
style.shape = "Beam"
vi_mode_style.shape = "Block"

[general]


live_config_reload = true
import = [ "~/.config/alacritty/tokyo-night-storm.toml" ]

[terminal]
